version: '3.1'

services:

  pgdb0:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
      POSTGRES_USER: test

    ports:
      - 5444:5432
    volumes:
      - ./sql:/sql

  pgdb1:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
      POSTGRES_USER: test

    ports:
      - 5445:5432
    volumes:
      - ./sql:/sql